// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: frame.proto
// Protobuf Java Version: 4.29.5

package com.earthtv;

public final class FrameProtos {
  private FrameProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 5,
      /* suffix= */ "",
      FrameProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Frame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Frame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013frame.proto\"\300\002\n\005Frame\022\020\n\010frame_id\030\001 \001(" +
      "\005\022\020\n\010video_id\030\002 \001(\005\022\025\n\rframe_item_id\030\003 \001" +
      "(\t\022\027\n\017frame_item_href\030\004 \001(\t\022\021\n\tblue_href" +
      "\030\005 \001(\t\022\022\n\ngreen_href\030\006 \001(\t\022\020\n\010red_href\030\007" +
      " \001(\t\022\017\n\007min_lon\030\010 \001(\001\022\017\n\007max_lon\030\t \001(\001\022\017" +
      "\n\007min_lat\030\n \001(\001\022\017\n\007max_lat\030\013 \001(\001\022\033\n\023coll" +
      "ection_time_utc\030\014 \001(\005\022\022\n\nimage_data\030\r \001(" +
      "\014\022\021\n\timg_width\030\016 \001(\005\022\022\n\nimg_height\030\017 \001(\005" +
      "\022\016\n\006status\030\020 \001(\005B\034\n\013com.earthtvB\013FramePr" +
      "otosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Frame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Frame_descriptor,
        new String[] { "FrameId", "VideoId", "FrameItemId", "FrameItemHref", "BlueHref", "GreenHref", "RedHref", "MinLon", "MaxLon", "MinLat", "MaxLat", "CollectionTimeUtc", "ImageData", "ImgWidth", "ImgHeight", "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
