// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: frame.proto
// Protobuf Java Version: 4.29.5

package com.earthtv;

/**
 * Protobuf type {@code Frame}
 */
public final class Frame extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Frame)
        FrameOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 5,
      /* suffix= */ "",
      Frame.class.getName());
  }
  // Use Frame.newBuilder() to construct.
  private Frame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Frame() {
    frameItemId_ = "";
    frameItemHref_ = "";
    blueHref_ = "";
    greenHref_ = "";
    redHref_ = "";
    imageData_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.earthtv.FrameProtos.internal_static_Frame_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.earthtv.FrameProtos.internal_static_Frame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.earthtv.Frame.class, com.earthtv.Frame.Builder.class);
  }

  public static final int FRAME_ID_FIELD_NUMBER = 1;
  private int frameId_ = 0;
  /**
   * <code>int32 frame_id = 1;</code>
   * @return The frameId.
   */
  @Override
  public int getFrameId() {
    return frameId_;
  }

  public static final int VIDEO_ID_FIELD_NUMBER = 2;
  private int videoId_ = 0;
  /**
   * <code>int32 video_id = 2;</code>
   * @return The videoId.
   */
  @Override
  public int getVideoId() {
    return videoId_;
  }

  public static final int FRAME_ITEM_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object frameItemId_ = "";
  /**
   * <code>string frame_item_id = 3;</code>
   * @return The frameItemId.
   */
  @Override
  public String getFrameItemId() {
    Object ref = frameItemId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      frameItemId_ = s;
      return s;
    }
  }
  /**
   * <code>string frame_item_id = 3;</code>
   * @return The bytes for frameItemId.
   */
  @Override
  public com.google.protobuf.ByteString
      getFrameItemIdBytes() {
    Object ref = frameItemId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      frameItemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRAME_ITEM_HREF_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object frameItemHref_ = "";
  /**
   * <code>string frame_item_href = 4;</code>
   * @return The frameItemHref.
   */
  @Override
  public String getFrameItemHref() {
    Object ref = frameItemHref_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      frameItemHref_ = s;
      return s;
    }
  }
  /**
   * <code>string frame_item_href = 4;</code>
   * @return The bytes for frameItemHref.
   */
  @Override
  public com.google.protobuf.ByteString
      getFrameItemHrefBytes() {
    Object ref = frameItemHref_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      frameItemHref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLUE_HREF_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object blueHref_ = "";
  /**
   * <code>string blue_href = 5;</code>
   * @return The blueHref.
   */
  @Override
  public String getBlueHref() {
    Object ref = blueHref_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blueHref_ = s;
      return s;
    }
  }
  /**
   * <code>string blue_href = 5;</code>
   * @return The bytes for blueHref.
   */
  @Override
  public com.google.protobuf.ByteString
      getBlueHrefBytes() {
    Object ref = blueHref_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      blueHref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GREEN_HREF_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object greenHref_ = "";
  /**
   * <code>string green_href = 6;</code>
   * @return The greenHref.
   */
  @Override
  public String getGreenHref() {
    Object ref = greenHref_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      greenHref_ = s;
      return s;
    }
  }
  /**
   * <code>string green_href = 6;</code>
   * @return The bytes for greenHref.
   */
  @Override
  public com.google.protobuf.ByteString
      getGreenHrefBytes() {
    Object ref = greenHref_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      greenHref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RED_HREF_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object redHref_ = "";
  /**
   * <code>string red_href = 7;</code>
   * @return The redHref.
   */
  @Override
  public String getRedHref() {
    Object ref = redHref_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      redHref_ = s;
      return s;
    }
  }
  /**
   * <code>string red_href = 7;</code>
   * @return The bytes for redHref.
   */
  @Override
  public com.google.protobuf.ByteString
      getRedHrefBytes() {
    Object ref = redHref_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      redHref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIN_LON_FIELD_NUMBER = 8;
  private double minLon_ = 0D;
  /**
   * <code>double min_lon = 8;</code>
   * @return The minLon.
   */
  @Override
  public double getMinLon() {
    return minLon_;
  }

  public static final int MAX_LON_FIELD_NUMBER = 9;
  private double maxLon_ = 0D;
  /**
   * <code>double max_lon = 9;</code>
   * @return The maxLon.
   */
  @Override
  public double getMaxLon() {
    return maxLon_;
  }

  public static final int MIN_LAT_FIELD_NUMBER = 10;
  private double minLat_ = 0D;
  /**
   * <code>double min_lat = 10;</code>
   * @return The minLat.
   */
  @Override
  public double getMinLat() {
    return minLat_;
  }

  public static final int MAX_LAT_FIELD_NUMBER = 11;
  private double maxLat_ = 0D;
  /**
   * <code>double max_lat = 11;</code>
   * @return The maxLat.
   */
  @Override
  public double getMaxLat() {
    return maxLat_;
  }

  public static final int COLLECTION_TIME_UTC_FIELD_NUMBER = 12;
  private int collectionTimeUtc_ = 0;
  /**
   * <code>int32 collection_time_utc = 12;</code>
   * @return The collectionTimeUtc.
   */
  @Override
  public int getCollectionTimeUtc() {
    return collectionTimeUtc_;
  }

  public static final int IMAGE_DATA_FIELD_NUMBER = 13;
  private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes image_data = 13;</code>
   * @return The imageData.
   */
  @Override
  public com.google.protobuf.ByteString getImageData() {
    return imageData_;
  }

  public static final int IMG_WIDTH_FIELD_NUMBER = 14;
  private int imgWidth_ = 0;
  /**
   * <code>int32 img_width = 14;</code>
   * @return The imgWidth.
   */
  @Override
  public int getImgWidth() {
    return imgWidth_;
  }

  public static final int IMG_HEIGHT_FIELD_NUMBER = 15;
  private int imgHeight_ = 0;
  /**
   * <code>int32 img_height = 15;</code>
   * @return The imgHeight.
   */
  @Override
  public int getImgHeight() {
    return imgHeight_;
  }

  public static final int STATUS_FIELD_NUMBER = 16;
  private int status_ = 0;
  /**
   * <code>int32 status = 16;</code>
   * @return The status.
   */
  @Override
  public int getStatus() {
    return status_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (frameId_ != 0) {
      output.writeInt32(1, frameId_);
    }
    if (videoId_ != 0) {
      output.writeInt32(2, videoId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frameItemId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, frameItemId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frameItemHref_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, frameItemHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blueHref_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, blueHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(greenHref_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, greenHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(redHref_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, redHref_);
    }
    if (Double.doubleToRawLongBits(minLon_) != 0) {
      output.writeDouble(8, minLon_);
    }
    if (Double.doubleToRawLongBits(maxLon_) != 0) {
      output.writeDouble(9, maxLon_);
    }
    if (Double.doubleToRawLongBits(minLat_) != 0) {
      output.writeDouble(10, minLat_);
    }
    if (Double.doubleToRawLongBits(maxLat_) != 0) {
      output.writeDouble(11, maxLat_);
    }
    if (collectionTimeUtc_ != 0) {
      output.writeInt32(12, collectionTimeUtc_);
    }
    if (!imageData_.isEmpty()) {
      output.writeBytes(13, imageData_);
    }
    if (imgWidth_ != 0) {
      output.writeInt32(14, imgWidth_);
    }
    if (imgHeight_ != 0) {
      output.writeInt32(15, imgHeight_);
    }
    if (status_ != 0) {
      output.writeInt32(16, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (frameId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, frameId_);
    }
    if (videoId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, videoId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frameItemId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, frameItemId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frameItemHref_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, frameItemHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blueHref_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, blueHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(greenHref_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, greenHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(redHref_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, redHref_);
    }
    if (Double.doubleToRawLongBits(minLon_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, minLon_);
    }
    if (Double.doubleToRawLongBits(maxLon_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, maxLon_);
    }
    if (Double.doubleToRawLongBits(minLat_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, minLat_);
    }
    if (Double.doubleToRawLongBits(maxLat_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, maxLat_);
    }
    if (collectionTimeUtc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, collectionTimeUtc_);
    }
    if (!imageData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, imageData_);
    }
    if (imgWidth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, imgWidth_);
    }
    if (imgHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, imgHeight_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.earthtv.Frame)) {
      return super.equals(obj);
    }
    com.earthtv.Frame other = (com.earthtv.Frame) obj;

    if (getFrameId()
        != other.getFrameId()) return false;
    if (getVideoId()
        != other.getVideoId()) return false;
    if (!getFrameItemId()
        .equals(other.getFrameItemId())) return false;
    if (!getFrameItemHref()
        .equals(other.getFrameItemHref())) return false;
    if (!getBlueHref()
        .equals(other.getBlueHref())) return false;
    if (!getGreenHref()
        .equals(other.getGreenHref())) return false;
    if (!getRedHref()
        .equals(other.getRedHref())) return false;
    if (Double.doubleToLongBits(getMinLon())
        != Double.doubleToLongBits(
            other.getMinLon())) return false;
    if (Double.doubleToLongBits(getMaxLon())
        != Double.doubleToLongBits(
            other.getMaxLon())) return false;
    if (Double.doubleToLongBits(getMinLat())
        != Double.doubleToLongBits(
            other.getMinLat())) return false;
    if (Double.doubleToLongBits(getMaxLat())
        != Double.doubleToLongBits(
            other.getMaxLat())) return false;
    if (getCollectionTimeUtc()
        != other.getCollectionTimeUtc()) return false;
    if (!getImageData()
        .equals(other.getImageData())) return false;
    if (getImgWidth()
        != other.getImgWidth()) return false;
    if (getImgHeight()
        != other.getImgHeight()) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FRAME_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFrameId();
    hash = (37 * hash) + VIDEO_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVideoId();
    hash = (37 * hash) + FRAME_ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFrameItemId().hashCode();
    hash = (37 * hash) + FRAME_ITEM_HREF_FIELD_NUMBER;
    hash = (53 * hash) + getFrameItemHref().hashCode();
    hash = (37 * hash) + BLUE_HREF_FIELD_NUMBER;
    hash = (53 * hash) + getBlueHref().hashCode();
    hash = (37 * hash) + GREEN_HREF_FIELD_NUMBER;
    hash = (53 * hash) + getGreenHref().hashCode();
    hash = (37 * hash) + RED_HREF_FIELD_NUMBER;
    hash = (53 * hash) + getRedHref().hashCode();
    hash = (37 * hash) + MIN_LON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getMinLon()));
    hash = (37 * hash) + MAX_LON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getMaxLon()));
    hash = (37 * hash) + MIN_LAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getMinLat()));
    hash = (37 * hash) + MAX_LAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getMaxLat()));
    hash = (37 * hash) + COLLECTION_TIME_UTC_FIELD_NUMBER;
    hash = (53 * hash) + getCollectionTimeUtc();
    hash = (37 * hash) + IMAGE_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImageData().hashCode();
    hash = (37 * hash) + IMG_WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getImgWidth();
    hash = (37 * hash) + IMG_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getImgHeight();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.earthtv.Frame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.earthtv.Frame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.earthtv.Frame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.earthtv.Frame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.earthtv.Frame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.earthtv.Frame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.earthtv.Frame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.earthtv.Frame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.earthtv.Frame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.earthtv.Frame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.earthtv.Frame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.earthtv.Frame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.earthtv.Frame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Frame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Frame)
      FrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.earthtv.FrameProtos.internal_static_Frame_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.earthtv.FrameProtos.internal_static_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.earthtv.Frame.class, com.earthtv.Frame.Builder.class);
    }

    // Construct using com.earthtv.Frame.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      frameId_ = 0;
      videoId_ = 0;
      frameItemId_ = "";
      frameItemHref_ = "";
      blueHref_ = "";
      greenHref_ = "";
      redHref_ = "";
      minLon_ = 0D;
      maxLon_ = 0D;
      minLat_ = 0D;
      maxLat_ = 0D;
      collectionTimeUtc_ = 0;
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      imgWidth_ = 0;
      imgHeight_ = 0;
      status_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.earthtv.FrameProtos.internal_static_Frame_descriptor;
    }

    @Override
    public com.earthtv.Frame getDefaultInstanceForType() {
      return com.earthtv.Frame.getDefaultInstance();
    }

    @Override
    public com.earthtv.Frame build() {
      com.earthtv.Frame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.earthtv.Frame buildPartial() {
      com.earthtv.Frame result = new com.earthtv.Frame(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.earthtv.Frame result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.frameId_ = frameId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.videoId_ = videoId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.frameItemId_ = frameItemId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.frameItemHref_ = frameItemHref_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.blueHref_ = blueHref_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.greenHref_ = greenHref_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.redHref_ = redHref_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.minLon_ = minLon_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.maxLon_ = maxLon_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.minLat_ = minLat_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.maxLat_ = maxLat_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.collectionTimeUtc_ = collectionTimeUtc_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.imageData_ = imageData_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.imgWidth_ = imgWidth_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.imgHeight_ = imgHeight_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.status_ = status_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.earthtv.Frame) {
        return mergeFrom((com.earthtv.Frame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.earthtv.Frame other) {
      if (other == com.earthtv.Frame.getDefaultInstance()) return this;
      if (other.getFrameId() != 0) {
        setFrameId(other.getFrameId());
      }
      if (other.getVideoId() != 0) {
        setVideoId(other.getVideoId());
      }
      if (!other.getFrameItemId().isEmpty()) {
        frameItemId_ = other.frameItemId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getFrameItemHref().isEmpty()) {
        frameItemHref_ = other.frameItemHref_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getBlueHref().isEmpty()) {
        blueHref_ = other.blueHref_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getGreenHref().isEmpty()) {
        greenHref_ = other.greenHref_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getRedHref().isEmpty()) {
        redHref_ = other.redHref_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getMinLon() != 0D) {
        setMinLon(other.getMinLon());
      }
      if (other.getMaxLon() != 0D) {
        setMaxLon(other.getMaxLon());
      }
      if (other.getMinLat() != 0D) {
        setMinLat(other.getMinLat());
      }
      if (other.getMaxLat() != 0D) {
        setMaxLat(other.getMaxLat());
      }
      if (other.getCollectionTimeUtc() != 0) {
        setCollectionTimeUtc(other.getCollectionTimeUtc());
      }
      if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
        setImageData(other.getImageData());
      }
      if (other.getImgWidth() != 0) {
        setImgWidth(other.getImgWidth());
      }
      if (other.getImgHeight() != 0) {
        setImgHeight(other.getImgHeight());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              frameId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              videoId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              frameItemId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              frameItemHref_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              blueHref_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              greenHref_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              redHref_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 65: {
              minLon_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 73: {
              maxLon_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            case 81: {
              minLat_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 89: {
              maxLat_ = input.readDouble();
              bitField0_ |= 0x00000400;
              break;
            } // case 89
            case 96: {
              collectionTimeUtc_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 106: {
              imageData_ = input.readBytes();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              imgWidth_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              imgHeight_ = input.readInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 128: {
              status_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int frameId_ ;
    /**
     * <code>int32 frame_id = 1;</code>
     * @return The frameId.
     */
    @Override
    public int getFrameId() {
      return frameId_;
    }
    /**
     * <code>int32 frame_id = 1;</code>
     * @param value The frameId to set.
     * @return This builder for chaining.
     */
    public Builder setFrameId(int value) {

      frameId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 frame_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      frameId_ = 0;
      onChanged();
      return this;
    }

    private int videoId_ ;
    /**
     * <code>int32 video_id = 2;</code>
     * @return The videoId.
     */
    @Override
    public int getVideoId() {
      return videoId_;
    }
    /**
     * <code>int32 video_id = 2;</code>
     * @param value The videoId to set.
     * @return This builder for chaining.
     */
    public Builder setVideoId(int value) {

      videoId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 video_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      videoId_ = 0;
      onChanged();
      return this;
    }

    private Object frameItemId_ = "";
    /**
     * <code>string frame_item_id = 3;</code>
     * @return The frameItemId.
     */
    public String getFrameItemId() {
      Object ref = frameItemId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        frameItemId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string frame_item_id = 3;</code>
     * @return The bytes for frameItemId.
     */
    public com.google.protobuf.ByteString
        getFrameItemIdBytes() {
      Object ref = frameItemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        frameItemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string frame_item_id = 3;</code>
     * @param value The frameItemId to set.
     * @return This builder for chaining.
     */
    public Builder setFrameItemId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      frameItemId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string frame_item_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameItemId() {
      frameItemId_ = getDefaultInstance().getFrameItemId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string frame_item_id = 3;</code>
     * @param value The bytes for frameItemId to set.
     * @return This builder for chaining.
     */
    public Builder setFrameItemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      frameItemId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object frameItemHref_ = "";
    /**
     * <code>string frame_item_href = 4;</code>
     * @return The frameItemHref.
     */
    public String getFrameItemHref() {
      Object ref = frameItemHref_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        frameItemHref_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string frame_item_href = 4;</code>
     * @return The bytes for frameItemHref.
     */
    public com.google.protobuf.ByteString
        getFrameItemHrefBytes() {
      Object ref = frameItemHref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        frameItemHref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string frame_item_href = 4;</code>
     * @param value The frameItemHref to set.
     * @return This builder for chaining.
     */
    public Builder setFrameItemHref(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      frameItemHref_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string frame_item_href = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameItemHref() {
      frameItemHref_ = getDefaultInstance().getFrameItemHref();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string frame_item_href = 4;</code>
     * @param value The bytes for frameItemHref to set.
     * @return This builder for chaining.
     */
    public Builder setFrameItemHrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      frameItemHref_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object blueHref_ = "";
    /**
     * <code>string blue_href = 5;</code>
     * @return The blueHref.
     */
    public String getBlueHref() {
      Object ref = blueHref_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blueHref_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string blue_href = 5;</code>
     * @return The bytes for blueHref.
     */
    public com.google.protobuf.ByteString
        getBlueHrefBytes() {
      Object ref = blueHref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        blueHref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blue_href = 5;</code>
     * @param value The blueHref to set.
     * @return This builder for chaining.
     */
    public Builder setBlueHref(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      blueHref_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string blue_href = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlueHref() {
      blueHref_ = getDefaultInstance().getBlueHref();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string blue_href = 5;</code>
     * @param value The bytes for blueHref to set.
     * @return This builder for chaining.
     */
    public Builder setBlueHrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      blueHref_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object greenHref_ = "";
    /**
     * <code>string green_href = 6;</code>
     * @return The greenHref.
     */
    public String getGreenHref() {
      Object ref = greenHref_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        greenHref_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string green_href = 6;</code>
     * @return The bytes for greenHref.
     */
    public com.google.protobuf.ByteString
        getGreenHrefBytes() {
      Object ref = greenHref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        greenHref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string green_href = 6;</code>
     * @param value The greenHref to set.
     * @return This builder for chaining.
     */
    public Builder setGreenHref(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      greenHref_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string green_href = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGreenHref() {
      greenHref_ = getDefaultInstance().getGreenHref();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string green_href = 6;</code>
     * @param value The bytes for greenHref to set.
     * @return This builder for chaining.
     */
    public Builder setGreenHrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      greenHref_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private Object redHref_ = "";
    /**
     * <code>string red_href = 7;</code>
     * @return The redHref.
     */
    public String getRedHref() {
      Object ref = redHref_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        redHref_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string red_href = 7;</code>
     * @return The bytes for redHref.
     */
    public com.google.protobuf.ByteString
        getRedHrefBytes() {
      Object ref = redHref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        redHref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string red_href = 7;</code>
     * @param value The redHref to set.
     * @return This builder for chaining.
     */
    public Builder setRedHref(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      redHref_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string red_href = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRedHref() {
      redHref_ = getDefaultInstance().getRedHref();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string red_href = 7;</code>
     * @param value The bytes for redHref to set.
     * @return This builder for chaining.
     */
    public Builder setRedHrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      redHref_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private double minLon_ ;
    /**
     * <code>double min_lon = 8;</code>
     * @return The minLon.
     */
    @Override
    public double getMinLon() {
      return minLon_;
    }
    /**
     * <code>double min_lon = 8;</code>
     * @param value The minLon to set.
     * @return This builder for chaining.
     */
    public Builder setMinLon(double value) {

      minLon_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>double min_lon = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinLon() {
      bitField0_ = (bitField0_ & ~0x00000080);
      minLon_ = 0D;
      onChanged();
      return this;
    }

    private double maxLon_ ;
    /**
     * <code>double max_lon = 9;</code>
     * @return The maxLon.
     */
    @Override
    public double getMaxLon() {
      return maxLon_;
    }
    /**
     * <code>double max_lon = 9;</code>
     * @param value The maxLon to set.
     * @return This builder for chaining.
     */
    public Builder setMaxLon(double value) {

      maxLon_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>double max_lon = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxLon() {
      bitField0_ = (bitField0_ & ~0x00000100);
      maxLon_ = 0D;
      onChanged();
      return this;
    }

    private double minLat_ ;
    /**
     * <code>double min_lat = 10;</code>
     * @return The minLat.
     */
    @Override
    public double getMinLat() {
      return minLat_;
    }
    /**
     * <code>double min_lat = 10;</code>
     * @param value The minLat to set.
     * @return This builder for chaining.
     */
    public Builder setMinLat(double value) {

      minLat_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>double min_lat = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinLat() {
      bitField0_ = (bitField0_ & ~0x00000200);
      minLat_ = 0D;
      onChanged();
      return this;
    }

    private double maxLat_ ;
    /**
     * <code>double max_lat = 11;</code>
     * @return The maxLat.
     */
    @Override
    public double getMaxLat() {
      return maxLat_;
    }
    /**
     * <code>double max_lat = 11;</code>
     * @param value The maxLat to set.
     * @return This builder for chaining.
     */
    public Builder setMaxLat(double value) {

      maxLat_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>double max_lat = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxLat() {
      bitField0_ = (bitField0_ & ~0x00000400);
      maxLat_ = 0D;
      onChanged();
      return this;
    }

    private int collectionTimeUtc_ ;
    /**
     * <code>int32 collection_time_utc = 12;</code>
     * @return The collectionTimeUtc.
     */
    @Override
    public int getCollectionTimeUtc() {
      return collectionTimeUtc_;
    }
    /**
     * <code>int32 collection_time_utc = 12;</code>
     * @param value The collectionTimeUtc to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionTimeUtc(int value) {

      collectionTimeUtc_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int32 collection_time_utc = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectionTimeUtc() {
      bitField0_ = (bitField0_ & ~0x00000800);
      collectionTimeUtc_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes image_data = 13;</code>
     * @return The imageData.
     */
    @Override
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }
    /**
     * <code>bytes image_data = 13;</code>
     * @param value The imageData to set.
     * @return This builder for chaining.
     */
    public Builder setImageData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      imageData_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>bytes image_data = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageData() {
      bitField0_ = (bitField0_ & ~0x00001000);
      imageData_ = getDefaultInstance().getImageData();
      onChanged();
      return this;
    }

    private int imgWidth_ ;
    /**
     * <code>int32 img_width = 14;</code>
     * @return The imgWidth.
     */
    @Override
    public int getImgWidth() {
      return imgWidth_;
    }
    /**
     * <code>int32 img_width = 14;</code>
     * @param value The imgWidth to set.
     * @return This builder for chaining.
     */
    public Builder setImgWidth(int value) {

      imgWidth_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 img_width = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearImgWidth() {
      bitField0_ = (bitField0_ & ~0x00002000);
      imgWidth_ = 0;
      onChanged();
      return this;
    }

    private int imgHeight_ ;
    /**
     * <code>int32 img_height = 15;</code>
     * @return The imgHeight.
     */
    @Override
    public int getImgHeight() {
      return imgHeight_;
    }
    /**
     * <code>int32 img_height = 15;</code>
     * @param value The imgHeight to set.
     * @return This builder for chaining.
     */
    public Builder setImgHeight(int value) {

      imgHeight_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 img_height = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearImgHeight() {
      bitField0_ = (bitField0_ & ~0x00004000);
      imgHeight_ = 0;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <code>int32 status = 16;</code>
     * @return The status.
     */
    @Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 16;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {

      status_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00008000);
      status_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Frame)
  }

  // @@protoc_insertion_point(class_scope:Frame)
  private static final com.earthtv.Frame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.earthtv.Frame();
  }

  public static com.earthtv.Frame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Frame>
      PARSER = new com.google.protobuf.AbstractParser<Frame>() {
    @Override
    public Frame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Frame> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Frame> getParserForType() {
    return PARSER;
  }

  @Override
  public com.earthtv.Frame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

