// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: frame.proto
// Protobuf Java Version: 4.29.5

package com.earthtv;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 frame_id = 1;</code>
   * @return The frameId.
   */
  int getFrameId();

  /**
   * <code>int32 video_id = 2;</code>
   * @return The videoId.
   */
  int getVideoId();

  /**
   * <code>string frame_item_id = 3;</code>
   * @return The frameItemId.
   */
  String getFrameItemId();
  /**
   * <code>string frame_item_id = 3;</code>
   * @return The bytes for frameItemId.
   */
  com.google.protobuf.ByteString
      getFrameItemIdBytes();

  /**
   * <code>string frame_item_href = 4;</code>
   * @return The frameItemHref.
   */
  String getFrameItemHref();
  /**
   * <code>string frame_item_href = 4;</code>
   * @return The bytes for frameItemHref.
   */
  com.google.protobuf.ByteString
      getFrameItemHrefBytes();

  /**
   * <code>string blue_href = 5;</code>
   * @return The blueHref.
   */
  String getBlueHref();
  /**
   * <code>string blue_href = 5;</code>
   * @return The bytes for blueHref.
   */
  com.google.protobuf.ByteString
      getBlueHrefBytes();

  /**
   * <code>string green_href = 6;</code>
   * @return The greenHref.
   */
  String getGreenHref();
  /**
   * <code>string green_href = 6;</code>
   * @return The bytes for greenHref.
   */
  com.google.protobuf.ByteString
      getGreenHrefBytes();

  /**
   * <code>string red_href = 7;</code>
   * @return The redHref.
   */
  String getRedHref();
  /**
   * <code>string red_href = 7;</code>
   * @return The bytes for redHref.
   */
  com.google.protobuf.ByteString
      getRedHrefBytes();

  /**
   * <code>double min_lon = 8;</code>
   * @return The minLon.
   */
  double getMinLon();

  /**
   * <code>double max_lon = 9;</code>
   * @return The maxLon.
   */
  double getMaxLon();

  /**
   * <code>double min_lat = 10;</code>
   * @return The minLat.
   */
  double getMinLat();

  /**
   * <code>double max_lat = 11;</code>
   * @return The maxLat.
   */
  double getMaxLat();

  /**
   * <code>int32 collection_time_utc = 12;</code>
   * @return The collectionTimeUtc.
   */
  int getCollectionTimeUtc();

  /**
   * <code>bytes image_data = 13;</code>
   * @return The imageData.
   */
  com.google.protobuf.ByteString getImageData();

  /**
   * <code>int32 img_width = 14;</code>
   * @return The imgWidth.
   */
  int getImgWidth();

  /**
   * <code>int32 img_height = 15;</code>
   * @return The imgHeight.
   */
  int getImgHeight();

  /**
   * <code>int32 status = 16;</code>
   * @return The status.
   */
  int getStatus();
}
