// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.29.5

package com.earthtv;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 video_id = 1;</code>
   * @return The videoId.
   */
  int getVideoId();

  /**
   * <code>int32 user_id = 2;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>int64 start = 3;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <code>int64 end = 4;</code>
   * @return The end.
   */
  long getEnd();

  /**
   * <code>double lon = 5;</code>
   * @return The lon.
   */
  double getLon();

  /**
   * <code>double lat = 6;</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double min_lon = 7;</code>
   * @return The minLon.
   */
  double getMinLon();

  /**
   * <code>double max_lon = 8;</code>
   * @return The maxLon.
   */
  double getMaxLon();

  /**
   * <code>double min_lat = 9;</code>
   * @return The minLat.
   */
  double getMinLat();

  /**
   * <code>double max_lat = 10;</code>
   * @return The maxLat.
   */
  double getMaxLat();

  /**
   * <code>int32 status = 11;</code>
   * @return The status.
   */
  int getStatus();
}
