// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.29.5

package com.earthtv;

public final class VideoProtos {
  private VideoProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 5,
      /* suffix= */ "",
      VideoProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Video_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013video.proto\"\264\001\n\005Video\022\020\n\010video_id\030\001 \001(" +
      "\005\022\017\n\007user_id\030\002 \001(\005\022\r\n\005start\030\003 \001(\003\022\013\n\003end" +
      "\030\004 \001(\003\022\013\n\003lon\030\005 \001(\001\022\013\n\003lat\030\006 \001(\001\022\017\n\007min_" +
      "lon\030\007 \001(\001\022\017\n\007max_lon\030\010 \001(\001\022\017\n\007min_lat\030\t " +
      "\001(\001\022\017\n\007max_lat\030\n \001(\001\022\016\n\006status\030\013 \001(\005B\034\n\013" +
      "com.earthtvB\013VideoProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Video_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Video_descriptor,
        new String[] { "VideoId", "UserId", "Start", "End", "Lon", "Lat", "MinLon", "MaxLon", "MinLat", "MaxLat", "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
