# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\"\xc0\x02\n\x05\x46rame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x10\n\x08video_id\x18\x02 \x01(\x05\x12\x15\n\rframe_item_id\x18\x03 \x01(\t\x12\x17\n\x0f\x66rame_item_href\x18\x04 \x01(\t\x12\x11\n\tblue_href\x18\x05 \x01(\t\x12\x12\n\ngreen_href\x18\x06 \x01(\t\x12\x10\n\x08red_href\x18\x07 \x01(\t\x12\x0f\n\x07min_lon\x18\x08 \x01(\x01\x12\x0f\n\x07max_lon\x18\t \x01(\x01\x12\x0f\n\x07min_lat\x18\n \x01(\x01\x12\x0f\n\x07max_lat\x18\x0b \x01(\x01\x12\x1b\n\x13\x63ollection_time_utc\x18\x0c \x01(\x05\x12\x12\n\nimage_data\x18\r \x01(\x0c\x12\x11\n\timg_width\x18\x0e \x01(\x05\x12\x12\n\nimg_height\x18\x0f \x01(\x05\x12\x0e\n\x06status\x18\x10 \x01(\x05\x42#\n\x12\x63om.earthtv.protosB\x0b\x46rameProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.earthtv.protosB\013FrameProtosP\001'
  _globals['_FRAME']._serialized_start=16
  _globals['_FRAME']._serialized_end=336
# @@protoc_insertion_point(module_scope)
