# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\"\xb4\x01\n\x05Video\x12\x10\n\x08video_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\r\n\x05start\x18\x03 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x03\x12\x0b\n\x03lon\x18\x05 \x01(\x01\x12\x0b\n\x03lat\x18\x06 \x01(\x01\x12\x0f\n\x07min_lon\x18\x07 \x01(\x01\x12\x0f\n\x07max_lon\x18\x08 \x01(\x01\x12\x0f\n\x07min_lat\x18\t \x01(\x01\x12\x0f\n\x07max_lat\x18\n \x01(\x01\x12\x0e\n\x06status\x18\x0b \x01(\x05\x42#\n\x12\x63om.earthtv.protosB\x0bVideoProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.earthtv.protosB\013VideoProtosP\001'
  _globals['_VIDEO']._serialized_start=16
  _globals['_VIDEO']._serialized_end=196
# @@protoc_insertion_point(module_scope)
