package com.earthtv.api;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video.proto
// Protobuf Java Version: 4.33.0

@com.google.protobuf.Generated
public final class VideoOuterClass extends com.google.protobuf.GeneratedFile {
    private VideoOuterClass() {}
    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 0,
                /* suffix= */ "",
                "VideoOuterClass");
    }
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface VideoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Video)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 video_id = 1;</code>
         * @return The videoId.
         */
        int getVideoId();

        /**
         * <code>int32 user_id = 2;</code>
         * @return The userId.
         */
        int getUserId();

        /**
         * <code>int64 start = 3;</code>
         * @return The start.
         */
        long getStart();

        /**
         * <code>int64 end = 4;</code>
         * @return The end.
         */
        long getEnd();

        /**
         * <code>double lon = 5;</code>
         * @return The lon.
         */
        double getLon();

        /**
         * <code>double lat = 6;</code>
         * @return The lat.
         */
        double getLat();

        /**
         * <code>double min_lon = 7;</code>
         * @return The minLon.
         */
        double getMinLon();

        /**
         * <code>double max_lon = 8;</code>
         * @return The maxLon.
         */
        double getMaxLon();

        /**
         * <code>double min_lat = 9;</code>
         * @return The minLat.
         */
        double getMinLat();

        /**
         * <code>double max_lat = 10;</code>
         * @return The maxLat.
         */
        double getMaxLat();

        /**
         * <code>int32 status = 11;</code>
         * @return The status.
         */
        int getStatus();
    }
    /**
     * Protobuf type {@code Video}
     */
    public static final class Video extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Video)
            VideoOrBuilder {
        private static final long serialVersionUID = 0L;
        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 33,
                    /* patch= */ 0,
                    /* suffix= */ "",
                    "Video");
        }
        // Use Video.newBuilder() to construct.
        private Video(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }
        private Video() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return VideoOuterClass.internal_static_Video_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return VideoOuterClass.internal_static_Video_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Video.class, Builder.class);
        }

        public static final int VIDEO_ID_FIELD_NUMBER = 1;
        private int videoId_ = 0;
        /**
         * <code>int32 video_id = 1;</code>
         * @return The videoId.
         */
        @Override
        public int getVideoId() {
            return videoId_;
        }

        public static final int USER_ID_FIELD_NUMBER = 2;
        private int userId_ = 0;
        /**
         * <code>int32 user_id = 2;</code>
         * @return The userId.
         */
        @Override
        public int getUserId() {
            return userId_;
        }

        public static final int START_FIELD_NUMBER = 3;
        private long start_ = 0L;
        /**
         * <code>int64 start = 3;</code>
         * @return The start.
         */
        @Override
        public long getStart() {
            return start_;
        }

        public static final int END_FIELD_NUMBER = 4;
        private long end_ = 0L;
        /**
         * <code>int64 end = 4;</code>
         * @return The end.
         */
        @Override
        public long getEnd() {
            return end_;
        }

        public static final int LON_FIELD_NUMBER = 5;
        private double lon_ = 0D;
        /**
         * <code>double lon = 5;</code>
         * @return The lon.
         */
        @Override
        public double getLon() {
            return lon_;
        }

        public static final int LAT_FIELD_NUMBER = 6;
        private double lat_ = 0D;
        /**
         * <code>double lat = 6;</code>
         * @return The lat.
         */
        @Override
        public double getLat() {
            return lat_;
        }

        public static final int MIN_LON_FIELD_NUMBER = 7;
        private double minLon_ = 0D;
        /**
         * <code>double min_lon = 7;</code>
         * @return The minLon.
         */
        @Override
        public double getMinLon() {
            return minLon_;
        }

        public static final int MAX_LON_FIELD_NUMBER = 8;
        private double maxLon_ = 0D;
        /**
         * <code>double max_lon = 8;</code>
         * @return The maxLon.
         */
        @Override
        public double getMaxLon() {
            return maxLon_;
        }

        public static final int MIN_LAT_FIELD_NUMBER = 9;
        private double minLat_ = 0D;
        /**
         * <code>double min_lat = 9;</code>
         * @return The minLat.
         */
        @Override
        public double getMinLat() {
            return minLat_;
        }

        public static final int MAX_LAT_FIELD_NUMBER = 10;
        private double maxLat_ = 0D;
        /**
         * <code>double max_lat = 10;</code>
         * @return The maxLat.
         */
        @Override
        public double getMaxLat() {
            return maxLat_;
        }

        public static final int STATUS_FIELD_NUMBER = 11;
        private int status_ = 0;
        /**
         * <code>int32 status = 11;</code>
         * @return The status.
         */
        @Override
        public int getStatus() {
            return status_;
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (videoId_ != 0) {
                output.writeInt32(1, videoId_);
            }
            if (userId_ != 0) {
                output.writeInt32(2, userId_);
            }
            if (start_ != 0L) {
                output.writeInt64(3, start_);
            }
            if (end_ != 0L) {
                output.writeInt64(4, end_);
            }
            if (Double.doubleToRawLongBits(lon_) != 0) {
                output.writeDouble(5, lon_);
            }
            if (Double.doubleToRawLongBits(lat_) != 0) {
                output.writeDouble(6, lat_);
            }
            if (Double.doubleToRawLongBits(minLon_) != 0) {
                output.writeDouble(7, minLon_);
            }
            if (Double.doubleToRawLongBits(maxLon_) != 0) {
                output.writeDouble(8, maxLon_);
            }
            if (Double.doubleToRawLongBits(minLat_) != 0) {
                output.writeDouble(9, minLat_);
            }
            if (Double.doubleToRawLongBits(maxLat_) != 0) {
                output.writeDouble(10, maxLat_);
            }
            if (status_ != 0) {
                output.writeInt32(11, status_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (videoId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, videoId_);
            }
            if (userId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, userId_);
            }
            if (start_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, start_);
            }
            if (end_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(4, end_);
            }
            if (Double.doubleToRawLongBits(lon_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(5, lon_);
            }
            if (Double.doubleToRawLongBits(lat_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(6, lat_);
            }
            if (Double.doubleToRawLongBits(minLon_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(7, minLon_);
            }
            if (Double.doubleToRawLongBits(maxLon_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(8, maxLon_);
            }
            if (Double.doubleToRawLongBits(minLat_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(9, minLat_);
            }
            if (Double.doubleToRawLongBits(maxLat_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(10, maxLat_);
            }
            if (status_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(11, status_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Video)) {
                return super.equals(obj);
            }
            Video other = (Video) obj;

            if (getVideoId()
                    != other.getVideoId()) return false;
            if (getUserId()
                    != other.getUserId()) return false;
            if (getStart()
                    != other.getStart()) return false;
            if (getEnd()
                    != other.getEnd()) return false;
            if (Double.doubleToLongBits(getLon())
                    != Double.doubleToLongBits(
                    other.getLon())) return false;
            if (Double.doubleToLongBits(getLat())
                    != Double.doubleToLongBits(
                    other.getLat())) return false;
            if (Double.doubleToLongBits(getMinLon())
                    != Double.doubleToLongBits(
                    other.getMinLon())) return false;
            if (Double.doubleToLongBits(getMaxLon())
                    != Double.doubleToLongBits(
                    other.getMaxLon())) return false;
            if (Double.doubleToLongBits(getMinLat())
                    != Double.doubleToLongBits(
                    other.getMinLat())) return false;
            if (Double.doubleToLongBits(getMaxLat())
                    != Double.doubleToLongBits(
                    other.getMaxLat())) return false;
            if (getStatus()
                    != other.getStatus()) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + VIDEO_ID_FIELD_NUMBER;
            hash = (53 * hash) + getVideoId();
            hash = (37 * hash) + USER_ID_FIELD_NUMBER;
            hash = (53 * hash) + getUserId();
            hash = (37 * hash) + START_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getStart());
            hash = (37 * hash) + END_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getEnd());
            hash = (37 * hash) + LON_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getLon()));
            hash = (37 * hash) + LAT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getLat()));
            hash = (37 * hash) + MIN_LON_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getMinLon()));
            hash = (37 * hash) + MAX_LON_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getMaxLon()));
            hash = (37 * hash) + MIN_LAT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getMinLat()));
            hash = (37 * hash) + MAX_LAT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getMaxLat()));
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + getStatus();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Video parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Video parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Video parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Video parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Video parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Video parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Video parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }
        public static Video parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Video parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Video parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Video parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }
        public static Video parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Video prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Video}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Video)
                VideoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return VideoOuterClass.internal_static_Video_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return VideoOuterClass.internal_static_Video_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Video.class, Builder.class);
            }

            // Construct using VideoOuterClass.Video.newBuilder()
            private Builder() {

            }

            private Builder(
                    BuilderParent parent) {
                super(parent);

            }
            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                videoId_ = 0;
                userId_ = 0;
                start_ = 0L;
                end_ = 0L;
                lon_ = 0D;
                lat_ = 0D;
                minLon_ = 0D;
                maxLon_ = 0D;
                minLat_ = 0D;
                maxLat_ = 0D;
                status_ = 0;
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return VideoOuterClass.internal_static_Video_descriptor;
            }

            @Override
            public Video getDefaultInstanceForType() {
                return Video.getDefaultInstance();
            }

            @Override
            public Video build() {
                Video result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Video buildPartial() {
                Video result = new Video(this);
                if (bitField0_ != 0) { buildPartial0(result); }
                onBuilt();
                return result;
            }

            private void buildPartial0(Video result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.videoId_ = videoId_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.userId_ = userId_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.start_ = start_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.end_ = end_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.lon_ = lon_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.lat_ = lat_;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.minLon_ = minLon_;
                }
                if (((from_bitField0_ & 0x00000080) != 0)) {
                    result.maxLon_ = maxLon_;
                }
                if (((from_bitField0_ & 0x00000100) != 0)) {
                    result.minLat_ = minLat_;
                }
                if (((from_bitField0_ & 0x00000200) != 0)) {
                    result.maxLat_ = maxLat_;
                }
                if (((from_bitField0_ & 0x00000400) != 0)) {
                    result.status_ = status_;
                }
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Video) {
                    return mergeFrom((Video)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Video other) {
                if (other == Video.getDefaultInstance()) return this;
                if (other.getVideoId() != 0) {
                    setVideoId(other.getVideoId());
                }
                if (other.getUserId() != 0) {
                    setUserId(other.getUserId());
                }
                if (other.getStart() != 0L) {
                    setStart(other.getStart());
                }
                if (other.getEnd() != 0L) {
                    setEnd(other.getEnd());
                }
                if (Double.doubleToRawLongBits(other.getLon()) != 0) {
                    setLon(other.getLon());
                }
                if (Double.doubleToRawLongBits(other.getLat()) != 0) {
                    setLat(other.getLat());
                }
                if (Double.doubleToRawLongBits(other.getMinLon()) != 0) {
                    setMinLon(other.getMinLon());
                }
                if (Double.doubleToRawLongBits(other.getMaxLon()) != 0) {
                    setMaxLon(other.getMaxLon());
                }
                if (Double.doubleToRawLongBits(other.getMinLat()) != 0) {
                    setMinLat(other.getMinLat());
                }
                if (Double.doubleToRawLongBits(other.getMaxLat()) != 0) {
                    setMaxLat(other.getMaxLat());
                }
                if (other.getStatus() != 0) {
                    setStatus(other.getStatus());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                videoId_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 16: {
                                userId_ = input.readInt32();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 24: {
                                start_ = input.readInt64();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            case 32: {
                                end_ = input.readInt64();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 32
                            case 41: {
                                lon_ = input.readDouble();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 41
                            case 49: {
                                lat_ = input.readDouble();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 49
                            case 57: {
                                minLon_ = input.readDouble();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 57
                            case 65: {
                                maxLon_ = input.readDouble();
                                bitField0_ |= 0x00000080;
                                break;
                            } // case 65
                            case 73: {
                                minLat_ = input.readDouble();
                                bitField0_ |= 0x00000100;
                                break;
                            } // case 73
                            case 81: {
                                maxLat_ = input.readDouble();
                                bitField0_ |= 0x00000200;
                                break;
                            } // case 81
                            case 88: {
                                status_ = input.readInt32();
                                bitField0_ |= 0x00000400;
                                break;
                            } // case 88
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }
            private int bitField0_;

            private int videoId_ ;
            /**
             * <code>int32 video_id = 1;</code>
             * @return The videoId.
             */
            @Override
            public int getVideoId() {
                return videoId_;
            }
            /**
             * <code>int32 video_id = 1;</code>
             * @param value The videoId to set.
             * @return This builder for chaining.
             */
            public Builder setVideoId(int value) {

                videoId_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>int32 video_id = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearVideoId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                videoId_ = 0;
                onChanged();
                return this;
            }

            private int userId_ ;
            /**
             * <code>int32 user_id = 2;</code>
             * @return The userId.
             */
            @Override
            public int getUserId() {
                return userId_;
            }
            /**
             * <code>int32 user_id = 2;</code>
             * @param value The userId to set.
             * @return This builder for chaining.
             */
            public Builder setUserId(int value) {

                userId_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }
            /**
             * <code>int32 user_id = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearUserId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                userId_ = 0;
                onChanged();
                return this;
            }

            private long start_ ;
            /**
             * <code>int64 start = 3;</code>
             * @return The start.
             */
            @Override
            public long getStart() {
                return start_;
            }
            /**
             * <code>int64 start = 3;</code>
             * @param value The start to set.
             * @return This builder for chaining.
             */
            public Builder setStart(long value) {

                start_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }
            /**
             * <code>int64 start = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearStart() {
                bitField0_ = (bitField0_ & ~0x00000004);
                start_ = 0L;
                onChanged();
                return this;
            }

            private long end_ ;
            /**
             * <code>int64 end = 4;</code>
             * @return The end.
             */
            @Override
            public long getEnd() {
                return end_;
            }
            /**
             * <code>int64 end = 4;</code>
             * @param value The end to set.
             * @return This builder for chaining.
             */
            public Builder setEnd(long value) {

                end_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }
            /**
             * <code>int64 end = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearEnd() {
                bitField0_ = (bitField0_ & ~0x00000008);
                end_ = 0L;
                onChanged();
                return this;
            }

            private double lon_ ;
            /**
             * <code>double lon = 5;</code>
             * @return The lon.
             */
            @Override
            public double getLon() {
                return lon_;
            }
            /**
             * <code>double lon = 5;</code>
             * @param value The lon to set.
             * @return This builder for chaining.
             */
            public Builder setLon(double value) {

                lon_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }
            /**
             * <code>double lon = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearLon() {
                bitField0_ = (bitField0_ & ~0x00000010);
                lon_ = 0D;
                onChanged();
                return this;
            }

            private double lat_ ;
            /**
             * <code>double lat = 6;</code>
             * @return The lat.
             */
            @Override
            public double getLat() {
                return lat_;
            }
            /**
             * <code>double lat = 6;</code>
             * @param value The lat to set.
             * @return This builder for chaining.
             */
            public Builder setLat(double value) {

                lat_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }
            /**
             * <code>double lat = 6;</code>
             * @return This builder for chaining.
             */
            public Builder clearLat() {
                bitField0_ = (bitField0_ & ~0x00000020);
                lat_ = 0D;
                onChanged();
                return this;
            }

            private double minLon_ ;
            /**
             * <code>double min_lon = 7;</code>
             * @return The minLon.
             */
            @Override
            public double getMinLon() {
                return minLon_;
            }
            /**
             * <code>double min_lon = 7;</code>
             * @param value The minLon to set.
             * @return This builder for chaining.
             */
            public Builder setMinLon(double value) {

                minLon_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }
            /**
             * <code>double min_lon = 7;</code>
             * @return This builder for chaining.
             */
            public Builder clearMinLon() {
                bitField0_ = (bitField0_ & ~0x00000040);
                minLon_ = 0D;
                onChanged();
                return this;
            }

            private double maxLon_ ;
            /**
             * <code>double max_lon = 8;</code>
             * @return The maxLon.
             */
            @Override
            public double getMaxLon() {
                return maxLon_;
            }
            /**
             * <code>double max_lon = 8;</code>
             * @param value The maxLon to set.
             * @return This builder for chaining.
             */
            public Builder setMaxLon(double value) {

                maxLon_ = value;
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }
            /**
             * <code>double max_lon = 8;</code>
             * @return This builder for chaining.
             */
            public Builder clearMaxLon() {
                bitField0_ = (bitField0_ & ~0x00000080);
                maxLon_ = 0D;
                onChanged();
                return this;
            }

            private double minLat_ ;
            /**
             * <code>double min_lat = 9;</code>
             * @return The minLat.
             */
            @Override
            public double getMinLat() {
                return minLat_;
            }
            /**
             * <code>double min_lat = 9;</code>
             * @param value The minLat to set.
             * @return This builder for chaining.
             */
            public Builder setMinLat(double value) {

                minLat_ = value;
                bitField0_ |= 0x00000100;
                onChanged();
                return this;
            }
            /**
             * <code>double min_lat = 9;</code>
             * @return This builder for chaining.
             */
            public Builder clearMinLat() {
                bitField0_ = (bitField0_ & ~0x00000100);
                minLat_ = 0D;
                onChanged();
                return this;
            }

            private double maxLat_ ;
            /**
             * <code>double max_lat = 10;</code>
             * @return The maxLat.
             */
            @Override
            public double getMaxLat() {
                return maxLat_;
            }
            /**
             * <code>double max_lat = 10;</code>
             * @param value The maxLat to set.
             * @return This builder for chaining.
             */
            public Builder setMaxLat(double value) {

                maxLat_ = value;
                bitField0_ |= 0x00000200;
                onChanged();
                return this;
            }
            /**
             * <code>double max_lat = 10;</code>
             * @return This builder for chaining.
             */
            public Builder clearMaxLat() {
                bitField0_ = (bitField0_ & ~0x00000200);
                maxLat_ = 0D;
                onChanged();
                return this;
            }

            private int status_ ;
            /**
             * <code>int32 status = 11;</code>
             * @return The status.
             */
            @Override
            public int getStatus() {
                return status_;
            }
            /**
             * <code>int32 status = 11;</code>
             * @param value The status to set.
             * @return This builder for chaining.
             */
            public Builder setStatus(int value) {

                status_ = value;
                bitField0_ |= 0x00000400;
                onChanged();
                return this;
            }
            /**
             * <code>int32 status = 11;</code>
             * @return This builder for chaining.
             */
            public Builder clearStatus() {
                bitField0_ = (bitField0_ & ~0x00000400);
                status_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Video)
        }

        // @@protoc_insertion_point(class_scope:Video)
        private static final Video DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Video();
        }

        public static Video getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Video>
                PARSER = new com.google.protobuf.AbstractParser<Video>() {
            @Override
            public Video parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Video> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Video> getParserForType() {
            return PARSER;
        }

        @Override
        public Video getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Video_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Video_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\013video.proto\"\264\001\n\005Video\022\020\n\010video_id\030\001 \001(" +
                        "\005\022\017\n\007user_id\030\002 \001(\005\022\r\n\005start\030\003 \001(\003\022\013\n\003end" +
                        "\030\004 \001(\003\022\013\n\003lon\030\005 \001(\001\022\013\n\003lat\030\006 \001(\001\022\017\n\007min_" +
                        "lon\030\007 \001(\001\022\017\n\007max_lon\030\010 \001(\001\022\017\n\007min_lat\030\t " +
                        "\001(\001\022\017\n\007max_lat\030\n \001(\001\022\016\n\006status\030\013 \001(\005b\006pr" +
                        "oto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_Video_descriptor =
                getDescriptor().getMessageType(0);
        internal_static_Video_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Video_descriptor,
                new String[] { "VideoId", "UserId", "Start", "End", "Lon", "Lat", "MinLon", "MaxLon", "MinLat", "MaxLat", "Status", });
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
